export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_CHECK = 'AUTH_CHECK';
export const AUTH_START = 'AUTH_START';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REDIRECT_PATH = 'AUTH_REDIRECT_PATH';


export const BOARDS_FETCH_START = 'BOARDS_FETCH_START';
export const BOARDS_FETCH_FAIL = 'BOARDS_FETCH_FAIL';
export const BOARDS_FETCH_SUCCESS = 'BOARDS_FETCH_SUCCESS';

export const TEMPLATES_FETCH_START = 'TEMPLATES_FETCH_START';
export const TEMPLATES_FETCH_FAIL = 'TEMPLATES_FETCH_FAIL';
export const TEMPLATES_FETCH_SUCCESS = 'TEMPLATES_FETCH_SUCCESS';